version: "3.5"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/django
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn movie_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django/
    expose:
      - "8000"
