# Generated by Django 3.1.7 on 2021-04-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='character name')),
                ('wc_url', models.URLField(verbose_name='wordcloud url')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='choice_content')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='question_content')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='sentiment name')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.choice')),
                ('sentiment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.sentiment')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('sentiment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.sentiment')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.question'),
        ),
    ]
