# Generated by Django 3.1.7 on 2021-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_img_url',
            field=models.URLField(default='', verbose_name='character img url'),
        ),
    ]
