# Generated by Django 3.1.7 on 2021-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20210412_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentcharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='sentimentcharacter',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='sentimentchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='sentimentchoice',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='character',
            name='bar_url',
            field=models.URLField(null=True, verbose_name='barchart url'),
        ),
        migrations.AddField(
            model_name='character',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='character',
            name='mvti_type',
            field=models.CharField(choices=[('negative', '긍정형'), ('postive', '부정형'), ('sadness', '비애형'), ('joy', '쾌락형'), ('anger', '분노형'),
                                   ('trust', '신뢰형'), ('fear', '근심형'), ('anticipation', '기대형')], max_length=12, null=True, verbose_name='MVTI_Type'),
        ),
        migrations.AddField(
            model_name='character',
            name='partner',
            field=models.CharField(max_length=100, null=True, verbose_name='partner'),
        ),
        migrations.AddField(
            model_name='character',
            name='rival',
            field=models.CharField(max_length=100, null=True, verbose_name='rival'),
        ),
        migrations.AddField(
            model_name='character',
            name='sentiment',
            field=models.JSONField(null=True, verbose_name='sentiment json'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wc_url',
            field=models.URLField(null=True, verbose_name='wordcloud url'),
        ),
        migrations.AlterModelTable(
            name='character',
            table='Characters',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.DeleteModel(
            name='SentimentCharacter',
        ),
        migrations.DeleteModel(
            name='SentimentChoice',
        ),
    ]
