# Generated by Django 3.1.7 on 2021-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20210414_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mvti_type',
            field=models.CharField(choices=[('NSAF', 'NSAF'), ('NSAA', 'NSAA'), ('NSTF', 'NSTF'), ('NSTA', 'NSTA'), ('NJAF', 'NJAF'), ('NJAA', 'NJAA'), ('NJTF', 'NJTF'), ('NJTA', 'NJTA'), ('PSAF', 'PSAF'), (
                'PSAA', 'PSAA'), ('PSTF', 'PSTF'), ('PSTA', 'PSTA'), ('PJAF', 'PJAF'), ('PJAA', 'PJAA'), ('PJTF', 'PJTF'), ('PJTA', 'PJTA')], max_length=12, null=True, verbose_name='MVTI_Type'),
        ),
    ]
