# Generated by Django 3.1.7 on 2021-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20210414_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='best_talk',
            field=models.CharField(max_length=100, null=True, verbose_name='best_talk'),
        ),
    ]
